Repository wwt/SwiftCurrent, pull requests merged in 2021-11, with the labels that each got.

#151 Removes jazzy from install steps when deploying new versions
  .github/workflows/trunk.yml
Labels: documentation, enhancement

#153 Fixes WorkflowLauncher to accept arguments when first FR has input of Never
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
Labels: bug

#150 Launching a Workflow using an AnyWorkflow
  Sources/SwiftCurrent/Models/FlowRepresentableMetadata.swift
  Sources/SwiftCurrent/TypeErased/AnyWorkflow.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/WorkflowExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Models/ExtendedFlowRepresentableMetadata.swift
  Sources/SwiftCurrent_SwiftUI/TypeErased/AnyWorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Tests/SwiftCurrentTests/FlowRepresentableMetadataConsumerTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
Labels: enhancement
