Repository wwt/SwiftCurrent, pull requests merged in 2021-08, with the labels that each got.

#91 Fixes issue with changing parent view state and vanishing Workflow Views
  Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
Labels: bug

#92 Updates links in README.md to show updated content
  README.md
  wiki/Getting-Started-Storyboard.md
  wiki/Getting-Started-SwiftUI.md
  wiki/Getting-Started-UIKit.md
Labels: bug, documentation

#94 Expands platform support to include macOS, watchOS, and tvOS.
  .github/SECURITY.md
  Package.swift
  Sources/SwiftCurrent/TestOnly/TestOnly.swift
  Sources/SwiftCurrent_UIKit/Extensions/LaunchStyleAdditions.swift
  SwiftCurrent.podspec
  fastlane/Fastfile
Labels: documentation, enhancement

#96 Fixes relaunching WorkflowViews
  Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  wiki/Getting-Started-SwiftUI.md
Labels: bug

#97 Adds interoperability between UIKit and SwiftUI to SwiftCurrent
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj
  ExampleApps/SwiftUIExample/SwiftUIExample/UIKitInterop/UIKitInteropProgrammaticViewController.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInterop.storyboard
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/ViewInspector/InspectableExtensions.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/SwiftUIInteropTests.swift
  ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
  Sources/SwiftCurrent_SwiftUI/UIKitInterop/HostedWorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Views/ViewControllerWrapper.swift
  Sources/SwiftCurrent_SwiftUI/WorkflowItem.swift
  wiki/Getting-Started-SwiftUI.md
  wiki/Getting-Started-UIKit.md
Labels: enhancement

#103 Adds ability to launchInto an `AnyWorkflow`
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/TestConstant.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerTests.swift
  ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
  Sources/SwiftCurrent_UIKit/Extensions/UIViewControllerAdditions.swift
Labels: enhancement

#104 Adds special thanks section to README that recognizes test dependencies
  README.md
Labels: documentation

#107 Changes to support library development on an M1 mac
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/StoryboardLoadableTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/TestUtilities/CustomAssertions.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitPresenterTests.swift
  SwiftCurrentLint/SwiftCurrentLint.xcodeproj/project.pbxproj
  Tests/SwiftCurrentTests/CustomAssertions.swift
  Tests/SwiftCurrentTests/LinkedListTests.swift
  Tests/SwiftCurrentTests/PassthroughFlowRepresentableTests.swift
  Tests/SwiftCurrentTests/WorkflowConsumerTests.swift
  Tests/SwiftCurrentTests/WorkflowTests.swift
  Tests/SwiftCurrent_SwiftUITests/CustomAssertions.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowItemTests.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowViewModelTests.swift
Labels: enhancement

#106 Adding section regarding commit message format to CONTRIBUTING.md.
  .github/CONTRIBUTING.md
Labels: documentation

#111 Redesigns SwiftUI API to enable the correct type nesting needing for NavigationLinks - See discussion #113
  .github/SwiftCurrentLint/.swiftlint.yml
  .github/wiki/Getting-Started-SwiftUI.md
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/ViewInspector/InspectableExtensions.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/ViewInspector/ViewHostingExtensions.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/AccountInformationViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ChangePasswordViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ContentViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/MapFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ProfileFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/QRScannerFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/Views/ContentView.swift
  ExampleApps/SwiftUIExample/Views/Profile/AccountInformationView.swift
  Package.swift
  README.md
  Sources/SwiftCurrent/Protocols/FlowRepresentable.swift
  Sources/SwiftCurrent/TypeErased/AnyWorkflow.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/AnyWorkflowElementExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/SwiftUILaunchStyleAdditions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/ViewExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Models/Launcher.swift
  Sources/SwiftCurrent_SwiftUI/Models/WorkflowViewModel.swift
  Sources/SwiftCurrent_SwiftUI/Protocols/WorkflowModifier.swift
  Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Sources/SwiftCurrent_SwiftUI/WorkflowItem.swift
  Tests/SwiftCurrentTests/WorkflowTests.swift
  Tests/SwiftCurrent_SwiftUITests/AnyFlowRepresentableViewTests.swift
  Tests/SwiftCurrent_SwiftUITests/AnyWorkflowTests.swift
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/SwiftCurrent_SwiftUITests/PersistenceTests.swift
  Tests/SwiftCurrent_SwiftUITests/SkipTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftUILaunchStyleAdditionTests.swift
  Tests/SwiftCurrent_SwiftUITests/TestExtensions/XCTestCaseExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/ViewHostingExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowItemExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowItemTests.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowViewModelTests.swift
Labels: enhancement
