Repository wwt/SwiftCurrent, pull requests merged in 2021-06, with the labels that each got.

#32 Removes deferred sections from Wiki and adds testing instructions to Getting Started.
  .gitignore
  README.md
  WorkflowExample/WorkflowExample/Base.lproj/Main.storyboard
  wiki/Advanced.md
  wiki/FAQ.md
  wiki/Getting-Started.md
  wiki/Home.md
  wiki/Testing-Your-Workflows.md
  wiki/Tutorial.md
  wiki/_Footer.md
Labels: cla-signed, documentation

#37 Creates Getting Started with Programmatic UIKit
  README.md
  wiki/Getting-Started-UIKit.md
  wiki/Home.md
Labels: cla-signed, documentation

#36 Improves import and installation documentation
  README.md
  wiki/Getting-Started-UIKit.md
  wiki/Getting-Started.md
  wiki/Installation.md
  wiki/Why-This-Library.md
Labels: cla-signed, documentation

#51 Enhances clarity and accuracy of Installation guide
  wiki/Getting-Started-UIKit.md
  wiki/Getting-Started.md
  wiki/Installation.md
Labels: cla-signed, documentation

#52 Replaces SonarCloud analysis with CodeCov in the pipeline.
  .github/.codecov.yml
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  .github/workflows/PR_CI.yml
  README.md
  SwiftCurrentLint/.swiftlint.yml
  sonar-project.properties
  xccov-to-sonarqube-generic.sh
Labels: cla-signed, enhancement

#54 Updates Codecov ignore list to correctly ignore items. Updates documentation release process.
  .clabot
  .github/.codecov.yml
  .github/workflows/trunk.yml
  docs/docsets/SwiftCurrent.tgz
Labels: cla-signed

#56 Bringing more exposure to Sample App
  README.md
  wiki/Getting-Started-UIKit.md
  wiki/Getting-Started.md
Labels: cla-signed, documentation

#58 Fixes doc generation and adds SPM badge
  .github/workflows/trunk.yml
  README.md
Labels: cla-signed, documentation

#60 Moving files out of root to make things easier to find.
  .github/.jazzy.yaml
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/STYLEGUIDE.md
  .github/changelog_configuration.json
  .github/document.sh
  .github/workflows/trunk.yml
  DynamicWorkflow.podspec
  Package.resolved
  Sources/SwiftCurrent/TypeErased/AnyFlowRepresentable.swift
  Sources/SwiftCurrent/TypeErased/AnyWorkflow.swift
  SwiftCurrent.xcworkspace/contents.xcworkspacedata
  fastlane/muter.conf.json
  wiki/UPGRADE_PATH.md
Labels: cla-signed

#63 Adds preference for attributes on the same line as what they attribute to the StyleGuide
  .github/STYLEGUIDE.md
Labels: cla-signed

#67 Updates pipeline to use Release Token
  .github/workflows/trunk.yml
Labels: cla-signed

#69 Changes CLA servicer
  .clabot
Labels: cla-signed
