Repository wwt/SwiftCurrent, pull requests merged in 2021-05, with the labels that each got.

#18 Fix typo in README
  README.md
Labels: cla-signed, documentation

#28 [xccov-improvements] - Added an early fail if file cannot be found fo…
  xccov-to-sonarqube-generic.sh
Labels: cla-signed

#29 Removing need for the Info.plist for versioning
  .github/workflows/trunk.yml
  fastlane/Fastfile
Labels: cla-signed

#31 Fixes issue when abandoning a multiple modal workflow
  Sources/WorkflowUIKit/UIKitPresenter.swift
  WorkflowExample/WorkflowUIKitTests/UIKitConsumerAbandonTests.swift
  WorkflowExample/WorkflowUIKitTests/UIKitConsumerWorkflowChainingTests.swift
Labels: bug, cla-signed
