Repository wwt/SwiftCurrent, pull requests merged in 2021-09, with the labels that each got.

#117 GitHub io documentation restructured.
  .github/.jazzy.yaml
  .github/UPGRADE_PATH.md
  .github/guides/Getting Started with SwiftUI.md
  .github/guides/Installation.md
  .github/guides/Programmatic UIKit Intro.md
  .github/guides/Using Programmatic Views.md
  .github/guides/Using Storyboards.md
  .github/guides/Why This Library.md
  .github/wiki/Getting-Started-Storyboard.md
  .github/wiki/Getting-Started-SwiftUI.md
  .github/wiki/Home.md
  .github/wiki/programmatic.gif
  .github/wiki/storyboard.gif
  .github/wiki/swiftUI.gif
  .github/wiki/swiftcurrent-logo.png
  README.md
Labels: documentation

#118 Now supporting sheets in SwiftUI!
  .github/.jazzy.yaml
  .github/guides/Working with Modals.md
  Sources/SwiftCurrent_SwiftUI/Extensions/SwiftUILaunchStyleAdditions.swift
  Sources/SwiftCurrent_SwiftUI/Protocols/WorkflowItemPresentable.swift
  Sources/SwiftCurrent_SwiftUI/ViewInspector/InspectableSheet.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_ModalTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftUILaunchStyleAdditionTests.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
Labels: documentation, enhancement

#121 Adds support for Full screen cover modal presentation style
  .github/SwiftCurrentLint/.swiftlint.yml
  .github/guides/Working with Modals.md
  ExampleApps/SwiftUIExample/SwiftCurrent_SwiftUI_UITests/Info.plist
  ExampleApps/SwiftUIExample/SwiftCurrent_SwiftUI_UITests/SwiftCurrent_SwiftUI_UITests.swift
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/xcshareddata/xcschemes/SwiftUIExample.xcscheme
  ExampleApps/SwiftUIExample/SwiftUIExample/SwiftUIExampleApp.swift
  ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestEnumerations.swift
  ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestView.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/SwiftUILaunchStyleAdditions.swift
  Sources/SwiftCurrent_SwiftUI/Protocols/WorkflowItemPresentable.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent.xcscheme
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftUILaunchStyleAdditionTests.swift
Labels: documentation, enhancement

#126 New docs
  .github/DocsPostProcessor/.gitignore
  .github/DocsPostProcessor/Package.swift
  .github/DocsPostProcessor/Sources/DocsPostProcessor/DocsPostProcessor.swift
  .github/DocsPostProcessor/Sources/DocsPostProcessor/main.swift
  .github/abstract/Controlling Presentation.md
  .github/abstract/Creating Workflows in SwiftUI.md
  .github/abstract/Creating Workflows in UIKit.md
  .github/abstract/Creating Workflows.md
  .github/abstract/How to use SwiftCurrent with UIKit.md
  .github/abstract/Type Erasure.md
  .github/abstract/Underlying Types.md
  .github/document.sh
  README.md
Labels: documentation

#127 Refactors to release SwiftUI support
  .github/abstract/Creating Workflows.md
  .github/fastlane/Fastfile
  .github/guides/Installation.md
  .github/guides/Using Programmatic Views.md
  .github/guides/Using Storyboards.md
  .github/rewrite-package-swift.sh
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/xcshareddata/xcschemes/SwiftUIExample.xcscheme
  ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestView.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
  ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
  Package.swift
  README.md
  Sources/SwiftCurrent/Models/Workflow.swift
  Sources/SwiftCurrent/Models/_WorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/AnyWorkflowElementExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/SwiftUIFlowPersistenceAdditions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/ThenProceedExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/ViewBuilderExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Models/WorkflowViewModel.swift
  Sources/SwiftCurrent_SwiftUI/Views/NavigationWrapper.swift
  Sources/SwiftCurrent_SwiftUI/Views/ViewControllerWrapper.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Sources/SwiftCurrent_UIKit/SwiftUIInterop/HostedWorkflowItem.swift
  SwiftCurrent.podspec
  SwiftCurrent.xcworkspace/xcshareddata/IDETemplateMacros.plist
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/SwiftCurrent_SwiftUITests/PersistenceTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_ModalTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/TestExtensions/XCTestCaseExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
Labels: enhancement

#128 SwiftUI is now out of Beta 🎉
  .github/.jazzy.yaml
  .github/DocsPostProcessor/.gitignore
  .github/DocsPostProcessor/Package.swift
  .github/DocsPostProcessor/Sources/DocsPostProcessor/DocsPostProcessor.swift
  .github/DocsPostProcessor/Sources/DocsPostProcessor/main.swift
  .github/abstract/Controlling Presentation.md
  .github/abstract/Creating Workflows in SwiftUI.md
  .github/abstract/Creating Workflows in UIKit.md
  .github/abstract/Creating Workflows.md
  .github/abstract/How to use SwiftCurrent with UIKit.md
  .github/abstract/Type Erasure.md
  .github/abstract/Underlying Types.md
  .github/document.sh
  .github/fastlane/Fastfile
  .github/guides/Getting Started with SwiftUI.md
  .github/guides/Installation.md
  .github/guides/Using Programmatic Views.md
  .github/guides/Using Storyboards.md
  .github/guides/Why This Library.md
  .github/rewrite-package-swift.sh
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/project.pbxproj
  ExampleApps/SwiftUIExample/SwiftUIExample.xcodeproj/xcshareddata/xcschemes/SwiftUIExample.xcscheme
  ExampleApps/SwiftUIExample/SwiftUIExample/TestViews/TestView.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
  ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
  Package.swift
  README.md
  Sources/SwiftCurrent/Models/Workflow.swift
  Sources/SwiftCurrent/Models/_WorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/AnyWorkflowElementExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/SwiftUIFlowPersistenceAdditions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/ThenProceedExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/ViewBuilderExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Models/WorkflowViewModel.swift
  Sources/SwiftCurrent_SwiftUI/Views/NavigationWrapper.swift
  Sources/SwiftCurrent_SwiftUI/Views/ViewControllerWrapper.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Sources/SwiftCurrent_UIKit/SwiftUIInterop/HostedWorkflowItem.swift
  SwiftCurrent.podspec
  SwiftCurrent.xcworkspace/xcshareddata/IDETemplateMacros.plist
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/SwiftCurrent_SwiftUITests/PersistenceTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_ModalTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/TestExtensions/XCTestCaseExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
Labels: enhancement

#131 Proofread and Made Minimal Changes to Creating Workflows in SwiftUI
  .github/abstract/Creating Workflows in SwiftUI.md
Labels: documentation

#132 Proofread and Made Minor Changes to Creating Workflows in UIKit
  .github/abstract/Creating Workflows in UIKit.md
Labels: documentation

#130 Proofread and made minimal changes to Controlling Presentation.
  .github/abstract/Controlling Presentation.md
Labels: documentation

#137 Proofread and Made Updates to Installation
  .github/guides/Installation.md
Labels: documentation

#135 Proofread and Made a Couple of Changes to Type Erasure
  .github/abstract/Type Erasure.md
Labels: documentation

#141 Update Working with Modals.md
  .github/guides/Working with Modals.md
Labels: documentation

#142 Proofread and Updated Working with NavigationView
  .github/guides/Working with NavigationView.md
Labels: documentation

#139 Updated Using Storyboards Guide
  .github/guides/Using Storyboards.md
Labels: documentation

#140 Updated Why This Library Section
  .github/guides/Why This Library.md
Labels: documentation

#138 Made changes to Using Programmatic Views Guide.
  .github/guides/Using Programmatic Views.md
Labels: documentation

#136 Made Changes to Getting Started with SwiftUI
  .github/guides/Getting Started with SwiftUI.md
Labels: documentation

#133 Made Changes to Creating Workflows Section
  .github/abstract/Creating Workflows.md
Labels: documentation

#134 Made Changes to How to use SwiftCurrent with UIKit Guide
  .github/abstract/How to use SwiftCurrent with UIKit.md
Labels: documentation

#129 Implements Mac/iOS Writing Standards for README
  README.md
Labels: documentation

#146 Updates API documentation based on technical writing suggestions.
  Sources/SwiftCurrent/Models/Workflow.swift
  Sources/SwiftCurrent/Protocols/FlowRepresentable.swift
  Sources/SwiftCurrent_UIKit/Extensions/UIViewControllerAdditions.swift
Labels: documentation
