Repository wwt/SwiftCurrent, pull requests merged in 2021-07, with the labels that each got.

#62 Enhances clarity of sample code and install.
  wiki/Getting-Started-UIKit.md
  wiki/Getting-Started.md
  wiki/Installation.md
  wiki/programmatic.gif
  wiki/storyboard.gif
Labels: cla-signed, documentation

#74 SwiftUI Documentation
  README.md
  wiki/Getting-Started-Storyboard.md
  wiki/Getting-Started-SwiftUI.md
  wiki/Getting-Started-UIKit.md
  wiki/Home.md
  wiki/Installation.md
  wiki/swiftUI.gif
Labels: documentation

#77 [Beta] Removes usage of AnyView
  ExampleApps/SwiftUIExample/README.md
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/ViewInspector/InspectableExtensions.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/AccountInformationViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ChangePasswordViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ContentViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/MapFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ProfileFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/QRScannerFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/Views/ContentView.swift
  ExampleApps/SwiftUIExample/Views/Profile/AccountInformationView.swift
  ExampleApps/SwiftUIExample/Views/Profile/ChangePasswordView.swift
  README.md
  Sources/SwiftCurrent/Protocols/FlowRepresentable.swift
  Sources/SwiftCurrent_SwiftUI/Models/WorkflowViewModel.swift
  Sources/SwiftCurrent_SwiftUI/TypeErased/AnyFlowRepresentableView.swift
  Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowView.swift
  Sources/SwiftCurrent_SwiftUI/WorkflowItem.swift
  SwiftCurrentLint/.swiftlint.yml
  Tests/SwiftCurrent_SwiftUITests/PersistenceTests.swift
  Tests/SwiftCurrent_SwiftUITests/SkipTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/InspectableExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowViewModelTests.swift
  wiki/Getting-Started-SwiftUI.md
Labels: enhancement

#78 Updates Contributing.md with CLA information
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#79 Adds Passthrough representable
  ExampleApps/SwiftUIExample/Views/MFAView.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/GenericConstraintTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/ModalStyleTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/StoryboardLoadableTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/TestStoryboard.storyboard
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerAbandonTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerLaunchTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerPersistenceTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerSkipTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitConsumerWorkflowChainingTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/UIKitPresenterTests.swift
  ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
  ExampleApps/UIKitExample/UIKitExample/SetupViewController.swift
  Sources/SwiftCurrent/Models/Workflow.swift
  Sources/SwiftCurrent/Protocols/PassthroughFlowRepresentable.swift
  Sources/SwiftCurrent/TypeErased/AnyFlowRepresentable.swift
  Sources/SwiftCurrent_SwiftUI/Views/ModifiedWorkflowView.swift
  Sources/SwiftCurrent_UIKit/Extensions/DeprecatedWorkflowUIKitAdditions.swift
  Sources/SwiftCurrent_UIKit/Extensions/WorkflowUIKitAdditions.swift
  Sources/SwiftCurrent_UIKit/StoryboardLoadable.swift
  SwiftCurrent.podspec
  Tests/SwiftCurrentTests/FlowPersistenceTests.swift
  Tests/SwiftCurrentTests/GenericConstraintTests.swift
  Tests/SwiftCurrentTests/WorkflowConsumerTests.swift
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/UIKitExampleTests/SetupViewControllerTests.swift
Labels: documentation, enhancement

#83 Update PR Template to direct contributors to remove unneeded checklist items
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#81 Fixes StoryboardLoadable protocol not working with AnyWorkflow.PassedArgs
  ExampleApps/UIKitExample/README.md
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/StoryboardLoadableTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/Storyboard/TestStoryboard.storyboard
  ExampleApps/UIKitExample/UIKitExample.xcodeproj/project.pbxproj
  ExampleApps/UIKitExample/UIKitExample/Base.lproj/Main.storyboard
  ExampleApps/UIKitExample/UIKitExample/SetupViewController.swift
  ExampleApps/UIKitExample/UIKitExample/TermsOfServiceViewController.swift
  ExampleApps/UIKitExample/UIKitExampleTests/TermsOfServiceViewControllerTests.swift
  Sources/SwiftCurrent/Protocols/FlowRepresentable.swift
  Sources/SwiftCurrent/TypeErased/AnyFlowRepresentable.swift
  Sources/SwiftCurrent_UIKit/StoryboardLoadable.swift
  Tests/SwiftCurrentTests/PassthroughFlowRepresentableTests.swift
  Tests/UIKitExampleTests/SetupViewControllerTests.swift
  Tests/UIKitExampleTests/TestFinder.swift
Labels: bug

#84 Adds a logo to the landing page
  README.md
  wiki/swiftcurrent-logo.png
Labels: documentation
