Repository wwt/SwiftCurrent, pull requests merged in 2022-03, with the labels that each got.

#185 The docs were using thenPresent but they should be using thenProceed
  .github/UPGRADE_PATH.md
  .github/abstract/Creating Workflows in UIKit.md
  .github/guides/Using Programmatic Views.md
  .github/guides/Using Storyboards.md
Labels: documentation

#191 Adds a section to the Contributing guidelines covering how to install SwiftLint.
  .github/CONTRIBUTING.md
Labels: documentation

#190 Fixes an issue where holding self weakly is causing a memory leak when calling workflow.abandon
  Sources/SwiftCurrent_UIKit/Extensions/WorkflowUIKitAdditions.swift
Labels: bug

#186 SwiftCurrent Intermediate Representation Generator
  .github/Matchfile
  .github/SwiftCurrentLint/SwiftCurrent-IRGeneratorTests/SwiftCurrent_IRGeneratorTests.swift
  .github/SwiftCurrentLint/SwiftCurrentLint.xcodeproj/project.pbxproj
  .github/SwiftCurrentLint/SwiftCurrentLint.xcodeproj/xcshareddata/xcbaselines/CA7B459827D196BB002EA040.xcbaseline/A4925EA8-DA56-4314-A2CC-1399FB60F370.plist
  .github/SwiftCurrentLint/SwiftCurrentLint.xcodeproj/xcshareddata/xcbaselines/CA7B459827D196BB002EA040.xcbaseline/Info.plist
  .github/fastlane/Fastfile
  .github/fastlane/README.md
  .github/workflows/CI.yml
  .github/workflows/PR_CI.yml
  Package.swift
  Sources/SwiftCurrent_IRGenerator/Commands/GenerateIR.swift
  Sources/SwiftCurrent_IRGenerator/Extensions/ArrayExtensions.swift
  Sources/SwiftCurrent_IRGenerator/Extensions/URLExtensions.swift
  Sources/SwiftCurrent_IRGenerator/Models/ConformingType.swift
  Sources/SwiftCurrent_IRGenerator/Models/Either.swift
  Sources/SwiftCurrent_IRGenerator/Parser/Declaration.swift
  Sources/SwiftCurrent_IRGenerator/Parser/File.swift
  Sources/SwiftCurrent_IRGenerator/Parser/SourceVisitor.swift
  Sources/SwiftCurrent_IRGenerator/Parser/SyntaxNode.swift
  Sources/SwiftCurrent_IRGenerator/Protocols/DeclarationSyntax.swift
  Sources/SwiftCurrent_IRGenerator/main.swift
  SwiftCurrent.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent_IRGenerator.xcscheme
Labels: enhancement

#196 Adds flow persistence decoding
  Sources/SwiftCurrent_SwiftUI/Extensions/WorkflowDecodableExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Models/ExtendedFlowRepresentableMetadata.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowItem.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowDecodableExtensionsTests.swift
Labels: enhancement

#197 Update URL Checker & Remove README Video
  .github/DocsPostProcessor/Sources/DocsPostProcessor/DocsPostProcessor.swift
  .github/document.sh
  .github/workflows/validate_urls.yml
  README.md
Labels: documentation, maintenance
