Repository wwt/SwiftCurrent, pull requests merged in 2022-01, with the labels that each got.

#158 Url checking upgrades
  .github/workflows/validate_urls.yml
Labels: enhancement

#159 Slack message fix
  .github/workflows/validate_urls.yml
Labels: bug

#157 Suggested changes to DocC
  Sources/SwiftCurrent/SwiftCurrent.docc/Tutorials/Core.tutorial
  SwiftCurrent.podspec
Labels: documentation

#155 Adds Metadata describer
  Sources/SwiftCurrent/Models/FlowRepresentableMetadata.swift
  Sources/SwiftCurrent/Protocols/FlowRepresentableMetadataDescriber.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/FlowRepresentableMetadataDescriberExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Models/ExtendedFlowRepresentableMetadata.swift
  Tests/SwiftCurrentTests/Metadata/FlowRepresentableMetadataConsumerTests.swift
  Tests/SwiftCurrentTests/Metadata/FlowRepresentableMetadataDescriberConsumerTests.swift
  Tests/SwiftCurrentTests/Metadata/FlowRepresentableMetadataTests.swift
  Tests/SwiftCurrent_SwiftUITests/FlowRepresentableMetadataDescriberExtensionsTests.swift
Labels: documentation, enhancement

#162 Fixed copyright linting
  .github/SwiftCurrentLint/.swiftlint.yml
Labels: bug

#161 Data drive json consumption
  .github/SwiftCurrentLint/.swiftlint.yml
  Sources/SwiftCurrent/Extensions/CollectionExtensions.swift
  Sources/SwiftCurrent/Extensions/DecoderExtensions.swift
  Sources/SwiftCurrent/PropertyWrappers/DecodeWorkflow.swift
  Sources/SwiftCurrent/Protocols/FlowRepresentableAggregator.swift
  Sources/SwiftCurrent/Protocols/WorkflowDecodable.swift
  Sources/SwiftCurrent/TypeErased/AnyWorkflow.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/WorkflowDecodableExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Extensions/WorkflowExtensions.swift
  Sources/SwiftCurrent_SwiftUI/Views/WorkflowLauncher.swift
  Sources/SwiftCurrent_Testing/TestRegistry.swift
  Tests/SwiftCurrentTests/JsonSpecificationTests.swift
  Tests/SwiftCurrentTests/Metadata/WorkflowDecodableConsumerTests.swift
  Tests/SwiftCurrent_SwiftUITests/AnyWorkflowTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowDecodableExtensionsTests.swift
Labels: documentation, enhancement

#160 Preview Providers now compile correctly
  Sources/SwiftCurrent_SwiftUI/Extensions/ThenProceedExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
Labels: bug
