Repository wwt/SwiftCurrent, pull requests merged in 2022-02, with the labels that each got.

#168 Implements eraseToAnyWorkflow function on Workflow.
  Sources/SwiftCurrent/Models/Workflow.swift
  Tests/SwiftCurrentTests/WorkflowConsumerTests.swift
Labels: documentation, enhancement

#170 Enabling the ability to handle default arguments in the json spec
  .github/fastlane/Fastfile
  .github/fastlane/README.md
  .github/workflows/PR_CI.yml
  Package.swift
  Sources/SwiftCurrent/Extensions/DecoderExtensions.swift
  SwiftCurrent.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  SwiftCurrent.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent.xcscheme
  SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrentMultiPlatformTests.xcscheme
  SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent_SwiftUI.xcscheme
  SwiftCurrent.xcworkspace/xcshareddata/xcschemes/SwiftCurrent_UIKit.xcscheme
  Tests/SwiftCurrentMultiPlatformTests/JsonSpecificationTests.swift
  Tests/SwiftCurrentTests/JsonSpecificationTests.swift
Labels: enhancement

#175 Removes Richard Gist as point of contact from Code of Conduct and replaces with Matt Hartfield.
  .github/CODE_OF_CONDUCT.md
Labels: documentation

#178 Moves class attributes onto new lines.
  .github/STYLEGUIDE.md
Labels: documentation

#171 Refactored SwiftUI tests to use async/await APIs
  .github/workflows/PR_CI.yml
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/UIKitInteropTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/AccountInformationViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ChangePasswordViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ChangeUsernameViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ContentViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/GenericOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/LoginTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/MFAViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/MapFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/MapFeatureViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/PasswordFieldTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/ProfileFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/QRScannerFeatureOnboardingViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/QRScanningViewTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/SignUpTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/SwiftCurrentOnboardingTests.swift
  ExampleApps/SwiftUIExample/SwiftUIExampleTests/Views/TermsAndConditionsTests.swift
  ExampleApps/UIKitExample/SwiftCurrent_UIKitTests/TestUtilities/TopViewController.swift
  Package.swift
  SwiftCurrent.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Tests/SwiftCurrent_SwiftUITests/AnyFlowRepresentableViewTests.swift
  Tests/SwiftCurrent_SwiftUITests/AnyWorkflowTests.swift
  Tests/SwiftCurrent_SwiftUITests/GenericConstraintTests.swift
  Tests/SwiftCurrent_SwiftUITests/PersistenceTests.swift
  Tests/SwiftCurrent_SwiftUITests/SkipTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_ModalTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_NavigationLinkTests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftCurrent_SwiftUITests.swift
  Tests/SwiftCurrent_SwiftUITests/SwiftUILaunchStyleAdditionTests.swift
  Tests/SwiftCurrent_SwiftUITests/TestExtensions/XCTestCaseExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/ViewInspector/ViewHostingExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowItemExtensions.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowItemTests.swift
  Tests/SwiftCurrent_SwiftUITests/WorkflowViewModelTests.swift
Labels: enhancement
